
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fwqtztrfspbotzvpemkn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ3cXR6dHJmc3Bib3R6dnBlbWtuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwNTAyMjcsImV4cCI6MjA2MjYyNjIyN30.ccuumRIh9lFn_4QAJ67QsiIkKjPrvb8L4GDFx1-52YU";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: localStorage
  }
});
