// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://shluolqufopjgtapugnx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNobHVvbHF1Zm9wamd0YXB1Z254Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NDgxMTQsImV4cCI6MjA3MDIyNDExNH0.1XJaB_gPl9dPlwqPNfUsXXpg4XUriTI3mLP2HnY1Aok";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});